# NGPT model configuration
defaults:
  - data
  - training
  - _self_

# Model type
type: "ngpt"

# Model-specific configuration
model_cfg:
  vocab_size: 50257
  num_layers: 12
  num_heads: 6
  model_dim: 768
  use_fp8: false

# Override training parameters if needed
num_iterations: 1750