# SEDD model configuration
defaults:
  - training

model_cfg:
  vocab_size: 50257
  n_ctx: 1024
  d_model: 768
  num_heads: 6
  n_layers: 12
  transition_type: "absorbing"
  noise_schedule: "mutual_info"
  num_timesteps: 1000
  absorbing_state_idx: -1
  lm_loss_weight: 1.0
  se_loss_weight: 1.0

# Override training parameters if needed
train_seq_len: 1024
num_iterations: 1750