# Default training configuration
train_files: "data/fineweb10B/fineweb_train_*.bin"
val_files: "data/fineweb10B/fineweb_val_*.bin"
val_tokens: 10485760
train_seq_len: 49152  # 48*1024
val_seq_len: 262144   # 4*64*1024
num_iterations: 1750
cooldown_frac: 0.45
val_loss_every: 125
save_checkpoint: false
use_liger: true
use_adam_mini: false
num_layers: 12
model_dim: 768
use_wandb: true
torch_compile: true
proj_fp8: false
bfloat16: false
BLOCK_SIZE: 128
IS_MODAL: false
sliding_window_size: null
num_selected_blocks: null
compress_block_size: null
selection_block_size: null